FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img0
RUN echo b3BlbiBTeXN0ZW0Kb3BlbiBTeXN0ZW0uSU8KCi8vLyBTcGxpdHMgdGhlIGRhdGEgaW50byB0aGUgY3JhdGVzIGFuZCB0aGUgaW5zdHJ1Y3Rpb25zCmxldCBjcmF0ZXNBbmRJbnN0cnVjdGlvbnMgZGF0YSA9CiAgICBsZXQgcmVjIGdldENyYXRlRGF0YSAoY3JSNIPSNIPpCg== | base64 -d > Day5.Script.fsx
RUN mkdir data && echo ICAgICAgICAgICAgW0ddIFtXXSAgICAgICAgIFtRXSAgICAKW1pdICAgICAgICAgW1FdIFtNXSAgICAgW0pdIFtGXSAgICAKW1ZdICAgICAgICAgW1ZdIFtTXSBbRl0gW05dIFtSXSAgICAKW1RdICAgICAgICAgW0ZdIFtDXSBbSF0gW0ZdIFtSNIPSNIPA5 | base64 -d > data/Day5.data.txt
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img1
COPY --from=img0 data/Day5.data.txt data/Day5.data.txt
COPY --from=img0 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img2
COPY --from=img1 data/Day5.data.txt data/Day5.data.txt
COPY --from=img1 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img3
COPY --from=img2 data/Day5.data.txt data/Day5.data.txt
COPY --from=img2 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img4
COPY --from=img3 data/Day5.data.txt data/Day5.data.txt
COPY --from=img3 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img5
COPY --from=img4 data/Day5.data.txt data/Day5.data.txt
COPY --from=img4 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img6
COPY --from=img5 data/Day5.data.txt data/Day5.data.txt
COPY --from=img5 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img7
COPY --from=img6 data/Day5.data.txt data/Day5.data.txt
COPY --from=img6 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img8
COPY --from=img7 data/Day5.data.txt data/Day5.data.txt
COPY --from=img7 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img9
COPY --from=img8 data/Day5.data.txt data/Day5.data.txt
COPY --from=img8 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img10
COPY --from=img9 data/Day5.data.txt data/Day5.data.txt
COPY --from=img9 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img11
COPY --from=img10 data/Day5.data.txt data/Day5.data.txt
COPY --from=img10 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img12
COPY --from=img11 data/Day5.data.txt data/Day5.data.txt
COPY --from=img11 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img13
COPY --from=img12 data/Day5.data.txt data/Day5.data.txt
COPY --from=img12 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img14
COPY --from=img13 data/Day5.data.txt data/Day5.data.txt
COPY --from=img13 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img15
COPY --from=img14 data/Day5.data.txt data/Day5.data.txt
COPY --from=img14 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img16
COPY --from=img15 data/Day5.data.txt data/Day5.data.txt
COPY --from=img15 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img17
COPY --from=img16 data/Day5.data.txt data/Day5.data.txt
COPY --from=img16 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img18
COPY --from=img17 data/Day5.data.txt data/Day5.data.txt
COPY --from=img17 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img19
COPY --from=img18 data/Day5.data.txt data/Day5.data.txt
COPY --from=img18 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img20
COPY --from=img19 data/Day5.data.txt data/Day5.data.txt
COPY --from=img19 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img21
COPY --from=img20 data/Day5.data.txt data/Day5.data.txt
COPY --from=img20 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img22
COPY --from=img21 data/Day5.data.txt data/Day5.data.txt
COPY --from=img21 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img23
COPY --from=img22 data/Day5.data.txt data/Day5.data.txt
COPY --from=img22 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img24
COPY --from=img23 data/Day5.data.txt data/Day5.data.txt
COPY --from=img23 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img25
COPY --from=img24 data/Day5.data.txt data/Day5.data.txt
COPY --from=img24 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img26
COPY --from=img25 data/Day5.data.txt data/Day5.data.txt
COPY --from=img25 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img27
COPY --from=img26 data/Day5.data.txt data/Day5.data.txt
COPY --from=img26 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img28
COPY --from=img27 data/Day5.data.txt data/Day5.data.txt
COPY --from=img27 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img29
COPY --from=img28 data/Day5.data.txt data/Day5.data.txt
COPY --from=img28 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img30
COPY --from=img29 data/Day5.data.txt data/Day5.data.txt
COPY --from=img29 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img31
COPY --from=img30 data/Day5.data.txt data/Day5.data.txt
COPY --from=img30 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img32
COPY --from=img31 data/Day5.data.txt data/Day5.data.txt
COPY --from=img31 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img33
COPY --from=img32 data/Day5.data.txt data/Day5.data.txt
COPY --from=img32 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img34
COPY --from=img33 data/Day5.data.txt data/Day5.data.txt
COPY --from=img33 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img35
COPY --from=img34 data/Day5.data.txt data/Day5.data.txt
COPY --from=img34 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img36
COPY --from=img35 data/Day5.data.txt data/Day5.data.txt
COPY --from=img35 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img37
COPY --from=img36 data/Day5.data.txt data/Day5.data.txt
COPY --from=img36 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img38
COPY --from=img37 data/Day5.data.txt data/Day5.data.txt
COPY --from=img37 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img39
COPY --from=img38 data/Day5.data.txt data/Day5.data.txt
COPY --from=img38 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img40
COPY --from=img39 data/Day5.data.txt data/Day5.data.txt
COPY --from=img39 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img41
COPY --from=img40 data/Day5.data.txt data/Day5.data.txt
COPY --from=img40 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img42
COPY --from=img41 data/Day5.data.txt data/Day5.data.txt
COPY --from=img41 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img43
COPY --from=img42 data/Day5.data.txt data/Day5.data.txt
COPY --from=img42 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img44
COPY --from=img43 data/Day5.data.txt data/Day5.data.txt
COPY --from=img43 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img45
COPY --from=img44 data/Day5.data.txt data/Day5.data.txt
COPY --from=img44 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img46
COPY --from=img45 data/Day5.data.txt data/Day5.data.txt
COPY --from=img45 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img47
COPY --from=img46 data/Day5.data.txt data/Day5.data.txt
COPY --from=img46 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img48
COPY --from=img47 data/Day5.data.txt data/Day5.data.txt
COPY --from=img47 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img49
COPY --from=img48 data/Day5.data.txt data/Day5.data.txt
COPY --from=img48 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img50
COPY --from=img49 data/Day5.data.txt data/Day5.data.txt
COPY --from=img49 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img51
COPY --from=img50 data/Day5.data.txt data/Day5.data.txt
COPY --from=img50 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img52
COPY --from=img51 data/Day5.data.txt data/Day5.data.txt
COPY --from=img51 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img53
COPY --from=img52 data/Day5.data.txt data/Day5.data.txt
COPY --from=img52 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img54
COPY --from=img53 data/Day5.data.txt data/Day5.data.txt
COPY --from=img53 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img55
COPY --from=img54 data/Day5.data.txt data/Day5.data.txt
COPY --from=img54 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img56
COPY --from=img55 data/Day5.data.txt data/Day5.data.txt
COPY --from=img55 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img57
COPY --from=img56 data/Day5.data.txt data/Day5.data.txt
COPY --from=img56 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img58
COPY --from=img57 data/Day5.data.txt data/Day5.data.txt
COPY --from=img57 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img59
COPY --from=img58 data/Day5.data.txt data/Day5.data.txt
COPY --from=img58 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img60
COPY --from=img59 data/Day5.data.txt data/Day5.data.txt
COPY --from=img59 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img61
COPY --from=img60 data/Day5.data.txt data/Day5.data.txt
COPY --from=img60 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img62
COPY --from=img61 data/Day5.data.txt data/Day5.data.txt
COPY --from=img61 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img63
COPY --from=img62 data/Day5.data.txt data/Day5.data.txt
COPY --from=img62 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img64
COPY --from=img63 data/Day5.data.txt data/Day5.data.txt
COPY --from=img63 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img65
COPY --from=img64 data/Day5.data.txt data/Day5.data.txt
COPY --from=img64 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img66
COPY --from=img65 data/Day5.data.txt data/Day5.data.txt
COPY --from=img65 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img67
COPY --from=img66 data/Day5.data.txt data/Day5.data.txt
COPY --from=img66 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img68
COPY --from=img67 data/Day5.data.txt data/Day5.data.txt
COPY --from=img67 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img69
COPY --from=img68 data/Day5.data.txt data/Day5.data.txt
COPY --from=img68 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img70
COPY --from=img69 data/Day5.data.txt data/Day5.data.txt
COPY --from=img69 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img71
COPY --from=img70 data/Day5.data.txt data/Day5.data.txt
COPY --from=img70 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img72
COPY --from=img71 data/Day5.data.txt data/Day5.data.txt
COPY --from=img71 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img73
COPY --from=img72 data/Day5.data.txt data/Day5.data.txt
COPY --from=img72 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img74
COPY --from=img73 data/Day5.data.txt data/Day5.data.txt
COPY --from=img73 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img75
COPY --from=img74 data/Day5.data.txt data/Day5.data.txt
COPY --from=img74 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img76
COPY --from=img75 data/Day5.data.txt data/Day5.data.txt
COPY --from=img75 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img77
COPY --from=img76 data/Day5.data.txt data/Day5.data.txt
COPY --from=img76 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img78
COPY --from=img77 data/Day5.data.txt data/Day5.data.txt
COPY --from=img77 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img79
COPY --from=img78 data/Day5.data.txt data/Day5.data.txt
COPY --from=img78 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img80
COPY --from=img79 data/Day5.data.txt data/Day5.data.txt
COPY --from=img79 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img81
COPY --from=img80 data/Day5.data.txt data/Day5.data.txt
COPY --from=img80 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img82
COPY --from=img81 data/Day5.data.txt data/Day5.data.txt
COPY --from=img81 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img83
COPY --from=img82 data/Day5.data.txt data/Day5.data.txt
COPY --from=img82 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img84
COPY --from=img83 data/Day5.data.txt data/Day5.data.txt
COPY --from=img83 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img85
COPY --from=img84 data/Day5.data.txt data/Day5.data.txt
COPY --from=img84 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img86
COPY --from=img85 data/Day5.data.txt data/Day5.data.txt
COPY --from=img85 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img87
COPY --from=img86 data/Day5.data.txt data/Day5.data.txt
COPY --from=img86 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img88
COPY --from=img87 data/Day5.data.txt data/Day5.data.txt
COPY --from=img87 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img89
COPY --from=img88 data/Day5.data.txt data/Day5.data.txt
COPY --from=img88 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img90
COPY --from=img89 data/Day5.data.txt data/Day5.data.txt
COPY --from=img89 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img91
COPY --from=img90 data/Day5.data.txt data/Day5.data.txt
COPY --from=img90 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img92
COPY --from=img91 data/Day5.data.txt data/Day5.data.txt
COPY --from=img91 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img93
COPY --from=img92 data/Day5.data.txt data/Day5.data.txt
COPY --from=img92 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img94
COPY --from=img93 data/Day5.data.txt data/Day5.data.txt
COPY --from=img93 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img95
COPY --from=img94 data/Day5.data.txt data/Day5.data.txt
COPY --from=img94 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img96
COPY --from=img95 data/Day5.data.txt data/Day5.data.txt
COPY --from=img95 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img97
COPY --from=img96 data/Day5.data.txt data/Day5.data.txt
COPY --from=img96 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img98
COPY --from=img97 data/Day5.data.txt data/Day5.data.txt
COPY --from=img97 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img99
COPY --from=img98 data/Day5.data.txt data/Day5.data.txt
COPY --from=img98 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img100
COPY --from=img99 data/Day5.data.txt data/Day5.data.txt
COPY --from=img99 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img101
COPY --from=img100 data/Day5.data.txt data/Day5.data.txt
COPY --from=img100 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img102
COPY --from=img101 data/Day5.data.txt data/Day5.data.txt
COPY --from=img101 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img103
COPY --from=img102 data/Day5.data.txt data/Day5.data.txt
COPY --from=img102 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img104
COPY --from=img103 data/Day5.data.txt data/Day5.data.txt
COPY --from=img103 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img105
COPY --from=img104 data/Day5.data.txt data/Day5.data.txt
COPY --from=img104 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img106
COPY --from=img105 data/Day5.data.txt data/Day5.data.txt
COPY --from=img105 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img107
COPY --from=img106 data/Day5.data.txt data/Day5.data.txt
COPY --from=img106 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img108
COPY --from=img107 data/Day5.data.txt data/Day5.data.txt
COPY --from=img107 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img109
COPY --from=img108 data/Day5.data.txt data/Day5.data.txt
COPY --from=img108 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img110
COPY --from=img109 data/Day5.data.txt data/Day5.data.txt
COPY --from=img109 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img111
COPY --from=img110 data/Day5.data.txt data/Day5.data.txt
COPY --from=img110 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img112
COPY --from=img111 data/Day5.data.txt data/Day5.data.txt
COPY --from=img111 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img113
COPY --from=img112 data/Day5.data.txt data/Day5.data.txt
COPY --from=img112 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img114
COPY --from=img113 data/Day5.data.txt data/Day5.data.txt
COPY --from=img113 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img115
COPY --from=img114 data/Day5.data.txt data/Day5.data.txt
COPY --from=img114 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img116
COPY --from=img115 data/Day5.data.txt data/Day5.data.txt
COPY --from=img115 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img117
COPY --from=img116 data/Day5.data.txt data/Day5.data.txt
COPY --from=img116 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img118
COPY --from=img117 data/Day5.data.txt data/Day5.data.txt
COPY --from=img117 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img119
COPY --from=img118 data/Day5.data.txt data/Day5.data.txt
COPY --from=img118 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img120
COPY --from=img119 data/Day5.data.txt data/Day5.data.txt
COPY --from=img119 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img121
COPY --from=img120 data/Day5.data.txt data/Day5.data.txt
COPY --from=img120 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img122
COPY --from=img121 data/Day5.data.txt data/Day5.data.txt
COPY --from=img121 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img123
COPY --from=img122 data/Day5.data.txt data/Day5.data.txt
COPY --from=img122 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img124
COPY --from=img123 data/Day5.data.txt data/Day5.data.txt
COPY --from=img123 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img125
COPY --from=img124 data/Day5.data.txt data/Day5.data.txt
COPY --from=img124 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img126
COPY --from=img125 data/Day5.data.txt data/Day5.data.txt
COPY --from=img125 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img127
COPY --from=img126 data/Day5.data.txt data/Day5.data.txt
COPY --from=img126 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img128
COPY --from=img127 data/Day5.data.txt data/Day5.data.txt
COPY --from=img127 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img129
COPY --from=img128 data/Day5.data.txt data/Day5.data.txt
COPY --from=img128 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img130
COPY --from=img129 data/Day5.data.txt data/Day5.data.txt
COPY --from=img129 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img131
COPY --from=img130 data/Day5.data.txt data/Day5.data.txt
COPY --from=img130 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img132
COPY --from=img131 data/Day5.data.txt data/Day5.data.txt
COPY --from=img131 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img133
COPY --from=img132 data/Day5.data.txt data/Day5.data.txt
COPY --from=img132 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img134
COPY --from=img133 data/Day5.data.txt data/Day5.data.txt
COPY --from=img133 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img135
COPY --from=img134 data/Day5.data.txt data/Day5.data.txt
COPY --from=img134 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img136
COPY --from=img135 data/Day5.data.txt data/Day5.data.txt
COPY --from=img135 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img137
COPY --from=img136 data/Day5.data.txt data/Day5.data.txt
COPY --from=img136 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img138
COPY --from=img137 data/Day5.data.txt data/Day5.data.txt
COPY --from=img137 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img139
COPY --from=img138 data/Day5.data.txt data/Day5.data.txt
COPY --from=img138 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img140
COPY --from=img139 data/Day5.data.txt data/Day5.data.txt
COPY --from=img139 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img141
COPY --from=img140 data/Day5.data.txt data/Day5.data.txt
COPY --from=img140 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img142
COPY --from=img141 data/Day5.data.txt data/Day5.data.txt
COPY --from=img141 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img143
COPY --from=img142 data/Day5.data.txt data/Day5.data.txt
COPY --from=img142 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img144
COPY --from=img143 data/Day5.data.txt data/Day5.data.txt
COPY --from=img143 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img145
COPY --from=img144 data/Day5.data.txt data/Day5.data.txt
COPY --from=img144 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img146
COPY --from=img145 data/Day5.data.txt data/Day5.data.txt
COPY --from=img145 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img147
COPY --from=img146 data/Day5.data.txt data/Day5.data.txt
COPY --from=img146 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img148
COPY --from=img147 data/Day5.data.txt data/Day5.data.txt
COPY --from=img147 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img149
COPY --from=img148 data/Day5.data.txt data/Day5.data.txt
COPY --from=img148 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img150
COPY --from=img149 data/Day5.data.txt data/Day5.data.txt
COPY --from=img149 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img151
COPY --from=img150 data/Day5.data.txt data/Day5.data.txt
COPY --from=img150 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img152
COPY --from=img151 data/Day5.data.txt data/Day5.data.txt
COPY --from=img151 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img153
COPY --from=img152 data/Day5.data.txt data/Day5.data.txt
COPY --from=img152 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img154
COPY --from=img153 data/Day5.data.txt data/Day5.data.txt
COPY --from=img153 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img155
COPY --from=img154 data/Day5.data.txt data/Day5.data.txt
COPY --from=img154 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img156
COPY --from=img155 data/Day5.data.txt data/Day5.data.txt
COPY --from=img155 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img157
COPY --from=img156 data/Day5.data.txt data/Day5.data.txt
COPY --from=img156 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img158
COPY --from=img157 data/Day5.data.txt data/Day5.data.txt
COPY --from=img157 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img159
COPY --from=img158 data/Day5.data.txt data/Day5.data.txt
COPY --from=img158 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img160
COPY --from=img159 data/Day5.data.txt data/Day5.data.txt
COPY --from=img159 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img161
COPY --from=img160 data/Day5.data.txt data/Day5.data.txt
COPY --from=img160 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img162
COPY --from=img161 data/Day5.data.txt data/Day5.data.txt
COPY --from=img161 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img163
COPY --from=img162 data/Day5.data.txt data/Day5.data.txt
COPY --from=img162 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img164
COPY --from=img163 data/Day5.data.txt data/Day5.data.txt
COPY --from=img163 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img165
COPY --from=img164 data/Day5.data.txt data/Day5.data.txt
COPY --from=img164 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img166
COPY --from=img165 data/Day5.data.txt data/Day5.data.txt
COPY --from=img165 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img167
COPY --from=img166 data/Day5.data.txt data/Day5.data.txt
COPY --from=img166 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img168
COPY --from=img167 data/Day5.data.txt data/Day5.data.txt
COPY --from=img167 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img169
COPY --from=img168 data/Day5.data.txt data/Day5.data.txt
COPY --from=img168 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img170
COPY --from=img169 data/Day5.data.txt data/Day5.data.txt
COPY --from=img169 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img171
COPY --from=img170 data/Day5.data.txt data/Day5.data.txt
COPY --from=img170 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img172
COPY --from=img171 data/Day5.data.txt data/Day5.data.txt
COPY --from=img171 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img173
COPY --from=img172 data/Day5.data.txt data/Day5.data.txt
COPY --from=img172 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img174
COPY --from=img173 data/Day5.data.txt data/Day5.data.txt
COPY --from=img173 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img175
COPY --from=img174 data/Day5.data.txt data/Day5.data.txt
COPY --from=img174 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img176
COPY --from=img175 data/Day5.data.txt data/Day5.data.txt
COPY --from=img175 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img177
COPY --from=img176 data/Day5.data.txt data/Day5.data.txt
COPY --from=img176 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img178
COPY --from=img177 data/Day5.data.txt data/Day5.data.txt
COPY --from=img177 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img179
COPY --from=img178 data/Day5.data.txt data/Day5.data.txt
COPY --from=img178 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img180
COPY --from=img179 data/Day5.data.txt data/Day5.data.txt
COPY --from=img179 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img181
COPY --from=img180 data/Day5.data.txt data/Day5.data.txt
COPY --from=img180 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img182
COPY --from=img181 data/Day5.data.txt data/Day5.data.txt
COPY --from=img181 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img183
COPY --from=img182 data/Day5.data.txt data/Day5.data.txt
COPY --from=img182 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img184
COPY --from=img183 data/Day5.data.txt data/Day5.data.txt
COPY --from=img183 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img185
COPY --from=img184 data/Day5.data.txt data/Day5.data.txt
COPY --from=img184 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img186
COPY --from=img185 data/Day5.data.txt data/Day5.data.txt
COPY --from=img185 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img187
COPY --from=img186 data/Day5.data.txt data/Day5.data.txt
COPY --from=img186 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img188
COPY --from=img187 data/Day5.data.txt data/Day5.data.txt
COPY --from=img187 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img189
COPY --from=img188 data/Day5.data.txt data/Day5.data.txt
COPY --from=img188 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img190
COPY --from=img189 data/Day5.data.txt data/Day5.data.txt
COPY --from=img189 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img191
COPY --from=img190 data/Day5.data.txt data/Day5.data.txt
COPY --from=img190 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img192
COPY --from=img191 data/Day5.data.txt data/Day5.data.txt
COPY --from=img191 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img193
COPY --from=img192 data/Day5.data.txt data/Day5.data.txt
COPY --from=img192 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img194
COPY --from=img193 data/Day5.data.txt data/Day5.data.txt
COPY --from=img193 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img195
COPY --from=img194 data/Day5.data.txt data/Day5.data.txt
COPY --from=img194 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img196
COPY --from=img195 data/Day5.data.txt data/Day5.data.txt
COPY --from=img195 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img197
COPY --from=img196 data/Day5.data.txt data/Day5.data.txt
COPY --from=img196 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img198
COPY --from=img197 data/Day5.data.txt data/Day5.data.txt
COPY --from=img197 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img199
COPY --from=img198 data/Day5.data.txt data/Day5.data.txt
COPY --from=img198 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img200
COPY --from=img199 data/Day5.data.txt data/Day5.data.txt
COPY --from=img199 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img201
COPY --from=img200 data/Day5.data.txt data/Day5.data.txt
COPY --from=img200 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img202
COPY --from=img201 data/Day5.data.txt data/Day5.data.txt
COPY --from=img201 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img203
COPY --from=img202 data/Day5.data.txt data/Day5.data.txt
COPY --from=img202 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img204
COPY --from=img203 data/Day5.data.txt data/Day5.data.txt
COPY --from=img203 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img205
COPY --from=img204 data/Day5.data.txt data/Day5.data.txt
COPY --from=img204 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img206
COPY --from=img205 data/Day5.data.txt data/Day5.data.txt
COPY --from=img205 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img207
COPY --from=img206 data/Day5.data.txt data/Day5.data.txt
COPY --from=img206 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img208
COPY --from=img207 data/Day5.data.txt data/Day5.data.txt
COPY --from=img207 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img209
COPY --from=img208 data/Day5.data.txt data/Day5.data.txt
COPY --from=img208 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img210
COPY --from=img209 data/Day5.data.txt data/Day5.data.txt
COPY --from=img209 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img211
COPY --from=img210 data/Day5.data.txt data/Day5.data.txt
COPY --from=img210 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img212
COPY --from=img211 data/Day5.data.txt data/Day5.data.txt
COPY --from=img211 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img213
COPY --from=img212 data/Day5.data.txt data/Day5.data.txt
COPY --from=img212 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img214
COPY --from=img213 data/Day5.data.txt data/Day5.data.txt
COPY --from=img213 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img215
COPY --from=img214 data/Day5.data.txt data/Day5.data.txt
COPY --from=img214 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img216
COPY --from=img215 data/Day5.data.txt data/Day5.data.txt
COPY --from=img215 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img217
COPY --from=img216 data/Day5.data.txt data/Day5.data.txt
COPY --from=img216 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img218
COPY --from=img217 data/Day5.data.txt data/Day5.data.txt
COPY --from=img217 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img219
COPY --from=img218 data/Day5.data.txt data/Day5.data.txt
COPY --from=img218 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img220
COPY --from=img219 data/Day5.data.txt data/Day5.data.txt
COPY --from=img219 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img221
COPY --from=img220 data/Day5.data.txt data/Day5.data.txt
COPY --from=img220 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img222
COPY --from=img221 data/Day5.data.txt data/Day5.data.txt
COPY --from=img221 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img223
COPY --from=img222 data/Day5.data.txt data/Day5.data.txt
COPY --from=img222 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img224
COPY --from=img223 data/Day5.data.txt data/Day5.data.txt
COPY --from=img223 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img225
COPY --from=img224 data/Day5.data.txt data/Day5.data.txt
COPY --from=img224 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img226
COPY --from=img225 data/Day5.data.txt data/Day5.data.txt
COPY --from=img225 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img227
COPY --from=img226 data/Day5.data.txt data/Day5.data.txt
COPY --from=img226 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img228
COPY --from=img227 data/Day5.data.txt data/Day5.data.txt
COPY --from=img227 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img229
COPY --from=img228 data/Day5.data.txt data/Day5.data.txt
COPY --from=img228 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img230
COPY --from=img229 data/Day5.data.txt data/Day5.data.txt
COPY --from=img229 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img231
COPY --from=img230 data/Day5.data.txt data/Day5.data.txt
COPY --from=img230 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img232
COPY --from=img231 data/Day5.data.txt data/Day5.data.txt
COPY --from=img231 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img233
COPY --from=img232 data/Day5.data.txt data/Day5.data.txt
COPY --from=img232 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img234
COPY --from=img233 data/Day5.data.txt data/Day5.data.txt
COPY --from=img233 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img235
COPY --from=img234 data/Day5.data.txt data/Day5.data.txt
COPY --from=img234 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img236
COPY --from=img235 data/Day5.data.txt data/Day5.data.txt
COPY --from=img235 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img237
COPY --from=img236 data/Day5.data.txt data/Day5.data.txt
COPY --from=img236 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img238
COPY --from=img237 data/Day5.data.txt data/Day5.data.txt
COPY --from=img237 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img239
COPY --from=img238 data/Day5.data.txt data/Day5.data.txt
COPY --from=img238 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img240
COPY --from=img239 data/Day5.data.txt data/Day5.data.txt
COPY --from=img239 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img241
COPY --from=img240 data/Day5.data.txt data/Day5.data.txt
COPY --from=img240 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img242
COPY --from=img241 data/Day5.data.txt data/Day5.data.txt
COPY --from=img241 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img243
COPY --from=img242 data/Day5.data.txt data/Day5.data.txt
COPY --from=img242 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img244
COPY --from=img243 data/Day5.data.txt data/Day5.data.txt
COPY --from=img243 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img245
COPY --from=img244 data/Day5.data.txt data/Day5.data.txt
COPY --from=img244 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img246
COPY --from=img245 data/Day5.data.txt data/Day5.data.txt
COPY --from=img245 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img247
COPY --from=img246 data/Day5.data.txt data/Day5.data.txt
COPY --from=img246 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img248
COPY --from=img247 data/Day5.data.txt data/Day5.data.txt
COPY --from=img247 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img249
COPY --from=img248 data/Day5.data.txt data/Day5.data.txt
COPY --from=img248 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img250
COPY --from=img249 data/Day5.data.txt data/Day5.data.txt
COPY --from=img249 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img251
COPY --from=img250 data/Day5.data.txt data/Day5.data.txt
COPY --from=img250 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img252
COPY --from=img251 data/Day5.data.txt data/Day5.data.txt
COPY --from=img251 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img253
COPY --from=img252 data/Day5.data.txt data/Day5.data.txt
COPY --from=img252 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img254
COPY --from=img253 data/Day5.data.txt data/Day5.data.txt
COPY --from=img253 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img255
COPY --from=img254 data/Day5.data.txt data/Day5.data.txt
COPY --from=img254 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img256
COPY --from=img255 data/Day5.data.txt data/Day5.data.txt
COPY --from=img255 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img257
COPY --from=img256 data/Day5.data.txt data/Day5.data.txt
COPY --from=img256 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img258
COPY --from=img257 data/Day5.data.txt data/Day5.data.txt
COPY --from=img257 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img259
COPY --from=img258 data/Day5.data.txt data/Day5.data.txt
COPY --from=img258 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img260
COPY --from=img259 data/Day5.data.txt data/Day5.data.txt
COPY --from=img259 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img261
COPY --from=img260 data/Day5.data.txt data/Day5.data.txt
COPY --from=img260 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img262
COPY --from=img261 data/Day5.data.txt data/Day5.data.txt
COPY --from=img261 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img263
COPY --from=img262 data/Day5.data.txt data/Day5.data.txt
COPY --from=img262 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img264
COPY --from=img263 data/Day5.data.txt data/Day5.data.txt
COPY --from=img263 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img265
COPY --from=img264 data/Day5.data.txt data/Day5.data.txt
COPY --from=img264 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img266
COPY --from=img265 data/Day5.data.txt data/Day5.data.txt
COPY --from=img265 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img267
COPY --from=img266 data/Day5.data.txt data/Day5.data.txt
COPY --from=img266 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img268
COPY --from=img267 data/Day5.data.txt data/Day5.data.txt
COPY --from=img267 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img269
COPY --from=img268 data/Day5.data.txt data/Day5.data.txt
COPY --from=img268 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img270
COPY --from=img269 data/Day5.data.txt data/Day5.data.txt
COPY --from=img269 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img271
COPY --from=img270 data/Day5.data.txt data/Day5.data.txt
COPY --from=img270 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img272
COPY --from=img271 data/Day5.data.txt data/Day5.data.txt
COPY --from=img271 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img273
COPY --from=img272 data/Day5.data.txt data/Day5.data.txt
COPY --from=img272 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img274
COPY --from=img273 data/Day5.data.txt data/Day5.data.txt
COPY --from=img273 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img275
COPY --from=img274 data/Day5.data.txt data/Day5.data.txt
COPY --from=img274 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img276
COPY --from=img275 data/Day5.data.txt data/Day5.data.txt
COPY --from=img275 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img277
COPY --from=img276 data/Day5.data.txt data/Day5.data.txt
COPY --from=img276 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img278
COPY --from=img277 data/Day5.data.txt data/Day5.data.txt
COPY --from=img277 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img279
COPY --from=img278 data/Day5.data.txt data/Day5.data.txt
COPY --from=img278 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img280
COPY --from=img279 data/Day5.data.txt data/Day5.data.txt
COPY --from=img279 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img281
COPY --from=img280 data/Day5.data.txt data/Day5.data.txt
COPY --from=img280 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img282
COPY --from=img281 data/Day5.data.txt data/Day5.data.txt
COPY --from=img281 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img283
COPY --from=img282 data/Day5.data.txt data/Day5.data.txt
COPY --from=img282 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img284
COPY --from=img283 data/Day5.data.txt data/Day5.data.txt
COPY --from=img283 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img285
COPY --from=img284 data/Day5.data.txt data/Day5.data.txt
COPY --from=img284 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img286
COPY --from=img285 data/Day5.data.txt data/Day5.data.txt
COPY --from=img285 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img287
COPY --from=img286 data/Day5.data.txt data/Day5.data.txt
COPY --from=img286 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img288
COPY --from=img287 data/Day5.data.txt data/Day5.data.txt
COPY --from=img287 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img289
COPY --from=img288 data/Day5.data.txt data/Day5.data.txt
COPY --from=img288 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img290
COPY --from=img289 data/Day5.data.txt data/Day5.data.txt
COPY --from=img289 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img291
COPY --from=img290 data/Day5.data.txt data/Day5.data.txt
COPY --from=img290 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img292
COPY --from=img291 data/Day5.data.txt data/Day5.data.txt
COPY --from=img291 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img293
COPY --from=img292 data/Day5.data.txt data/Day5.data.txt
COPY --from=img292 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img294
COPY --from=img293 data/Day5.data.txt data/Day5.data.txt
COPY --from=img293 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img295
COPY --from=img294 data/Day5.data.txt data/Day5.data.txt
COPY --from=img294 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img296
COPY --from=img295 data/Day5.data.txt data/Day5.data.txt
COPY --from=img295 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img297
COPY --from=img296 data/Day5.data.txt data/Day5.data.txt
COPY --from=img296 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img298
COPY --from=img297 data/Day5.data.txt data/Day5.data.txt
COPY --from=img297 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img299
COPY --from=img298 data/Day5.data.txt data/Day5.data.txt
COPY --from=img298 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img300
COPY --from=img299 data/Day5.data.txt data/Day5.data.txt
COPY --from=img299 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img301
COPY --from=img300 data/Day5.data.txt data/Day5.data.txt
COPY --from=img300 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img302
COPY --from=img301 data/Day5.data.txt data/Day5.data.txt
COPY --from=img301 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img303
COPY --from=img302 data/Day5.data.txt data/Day5.data.txt
COPY --from=img302 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img304
COPY --from=img303 data/Day5.data.txt data/Day5.data.txt
COPY --from=img303 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img305
COPY --from=img304 data/Day5.data.txt data/Day5.data.txt
COPY --from=img304 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img306
COPY --from=img305 data/Day5.data.txt data/Day5.data.txt
COPY --from=img305 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img307
COPY --from=img306 data/Day5.data.txt data/Day5.data.txt
COPY --from=img306 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img308
COPY --from=img307 data/Day5.data.txt data/Day5.data.txt
COPY --from=img307 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img309
COPY --from=img308 data/Day5.data.txt data/Day5.data.txt
COPY --from=img308 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img310
COPY --from=img309 data/Day5.data.txt data/Day5.data.txt
COPY --from=img309 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img311
COPY --from=img310 data/Day5.data.txt data/Day5.data.txt
COPY --from=img310 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img312
COPY --from=img311 data/Day5.data.txt data/Day5.data.txt
COPY --from=img311 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img313
COPY --from=img312 data/Day5.data.txt data/Day5.data.txt
COPY --from=img312 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img314
COPY --from=img313 data/Day5.data.txt data/Day5.data.txt
COPY --from=img313 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img315
COPY --from=img314 data/Day5.data.txt data/Day5.data.txt
COPY --from=img314 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img316
COPY --from=img315 data/Day5.data.txt data/Day5.data.txt
COPY --from=img315 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img317
COPY --from=img316 data/Day5.data.txt data/Day5.data.txt
COPY --from=img316 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img318
COPY --from=img317 data/Day5.data.txt data/Day5.data.txt
COPY --from=img317 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img319
COPY --from=img318 data/Day5.data.txt data/Day5.data.txt
COPY --from=img318 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img320
COPY --from=img319 data/Day5.data.txt data/Day5.data.txt
COPY --from=img319 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img321
COPY --from=img320 data/Day5.data.txt data/Day5.data.txt
COPY --from=img320 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img322
COPY --from=img321 data/Day5.data.txt data/Day5.data.txt
COPY --from=img321 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img323
COPY --from=img322 data/Day5.data.txt data/Day5.data.txt
COPY --from=img322 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img324
COPY --from=img323 data/Day5.data.txt data/Day5.data.txt
COPY --from=img323 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img325
COPY --from=img324 data/Day5.data.txt data/Day5.data.txt
COPY --from=img324 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img326
COPY --from=img325 data/Day5.data.txt data/Day5.data.txt
COPY --from=img325 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img327
COPY --from=img326 data/Day5.data.txt data/Day5.data.txt
COPY --from=img326 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img328
COPY --from=img327 data/Day5.data.txt data/Day5.data.txt
COPY --from=img327 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img329
COPY --from=img328 data/Day5.data.txt data/Day5.data.txt
COPY --from=img328 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img330
COPY --from=img329 data/Day5.data.txt data/Day5.data.txt
COPY --from=img329 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img331
COPY --from=img330 data/Day5.data.txt data/Day5.data.txt
COPY --from=img330 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img332
COPY --from=img331 data/Day5.data.txt data/Day5.data.txt
COPY --from=img331 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img333
COPY --from=img332 data/Day5.data.txt data/Day5.data.txt
COPY --from=img332 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img334
COPY --from=img333 data/Day5.data.txt data/Day5.data.txt
COPY --from=img333 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img335
COPY --from=img334 data/Day5.data.txt data/Day5.data.txt
COPY --from=img334 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img336
COPY --from=img335 data/Day5.data.txt data/Day5.data.txt
COPY --from=img335 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img337
COPY --from=img336 data/Day5.data.txt data/Day5.data.txt
COPY --from=img336 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img338
COPY --from=img337 data/Day5.data.txt data/Day5.data.txt
COPY --from=img337 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img339
COPY --from=img338 data/Day5.data.txt data/Day5.data.txt
COPY --from=img338 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img340
COPY --from=img339 data/Day5.data.txt data/Day5.data.txt
COPY --from=img339 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img341
COPY --from=img340 data/Day5.data.txt data/Day5.data.txt
COPY --from=img340 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img342
COPY --from=img341 data/Day5.data.txt data/Day5.data.txt
COPY --from=img341 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img343
COPY --from=img342 data/Day5.data.txt data/Day5.data.txt
COPY --from=img342 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img344
COPY --from=img343 data/Day5.data.txt data/Day5.data.txt
COPY --from=img343 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img345
COPY --from=img344 data/Day5.data.txt data/Day5.data.txt
COPY --from=img344 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img346
COPY --from=img345 data/Day5.data.txt data/Day5.data.txt
COPY --from=img345 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img347
COPY --from=img346 data/Day5.data.txt data/Day5.data.txt
COPY --from=img346 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img348
COPY --from=img347 data/Day5.data.txt data/Day5.data.txt
COPY --from=img347 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img349
COPY --from=img348 data/Day5.data.txt data/Day5.data.txt
COPY --from=img348 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img350
COPY --from=img349 data/Day5.data.txt data/Day5.data.txt
COPY --from=img349 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img351
COPY --from=img350 data/Day5.data.txt data/Day5.data.txt
COPY --from=img350 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img352
COPY --from=img351 data/Day5.data.txt data/Day5.data.txt
COPY --from=img351 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img353
COPY --from=img352 data/Day5.data.txt data/Day5.data.txt
COPY --from=img352 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img354
COPY --from=img353 data/Day5.data.txt data/Day5.data.txt
COPY --from=img353 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img355
COPY --from=img354 data/Day5.data.txt data/Day5.data.txt
COPY --from=img354 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img356
COPY --from=img355 data/Day5.data.txt data/Day5.data.txt
COPY --from=img355 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img357
COPY --from=img356 data/Day5.data.txt data/Day5.data.txt
COPY --from=img356 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img358
COPY --from=img357 data/Day5.data.txt data/Day5.data.txt
COPY --from=img357 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img359
COPY --from=img358 data/Day5.data.txt data/Day5.data.txt
COPY --from=img358 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img360
COPY --from=img359 data/Day5.data.txt data/Day5.data.txt
COPY --from=img359 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img361
COPY --from=img360 data/Day5.data.txt data/Day5.data.txt
COPY --from=img360 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img362
COPY --from=img361 data/Day5.data.txt data/Day5.data.txt
COPY --from=img361 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img363
COPY --from=img362 data/Day5.data.txt data/Day5.data.txt
COPY --from=img362 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img364
COPY --from=img363 data/Day5.data.txt data/Day5.data.txt
COPY --from=img363 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img365
COPY --from=img364 data/Day5.data.txt data/Day5.data.txt
COPY --from=img364 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img366
COPY --from=img365 data/Day5.data.txt data/Day5.data.txt
COPY --from=img365 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img367
COPY --from=img366 data/Day5.data.txt data/Day5.data.txt
COPY --from=img366 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img368
COPY --from=img367 data/Day5.data.txt data/Day5.data.txt
COPY --from=img367 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img369
COPY --from=img368 data/Day5.data.txt data/Day5.data.txt
COPY --from=img368 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img370
COPY --from=img369 data/Day5.data.txt data/Day5.data.txt
COPY --from=img369 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img371
COPY --from=img370 data/Day5.data.txt data/Day5.data.txt
COPY --from=img370 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img372
COPY --from=img371 data/Day5.data.txt data/Day5.data.txt
COPY --from=img371 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img373
COPY --from=img372 data/Day5.data.txt data/Day5.data.txt
COPY --from=img372 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img374
COPY --from=img373 data/Day5.data.txt data/Day5.data.txt
COPY --from=img373 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img375
COPY --from=img374 data/Day5.data.txt data/Day5.data.txt
COPY --from=img374 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img376
COPY --from=img375 data/Day5.data.txt data/Day5.data.txt
COPY --from=img375 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img377
COPY --from=img376 data/Day5.data.txt data/Day5.data.txt
COPY --from=img376 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img378
COPY --from=img377 data/Day5.data.txt data/Day5.data.txt
COPY --from=img377 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img379
COPY --from=img378 data/Day5.data.txt data/Day5.data.txt
COPY --from=img378 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img380
COPY --from=img379 data/Day5.data.txt data/Day5.data.txt
COPY --from=img379 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img381
COPY --from=img380 data/Day5.data.txt data/Day5.data.txt
COPY --from=img380 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img382
COPY --from=img381 data/Day5.data.txt data/Day5.data.txt
COPY --from=img381 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img383
COPY --from=img382 data/Day5.data.txt data/Day5.data.txt
COPY --from=img382 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img384
COPY --from=img383 data/Day5.data.txt data/Day5.data.txt
COPY --from=img383 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img385
COPY --from=img384 data/Day5.data.txt data/Day5.data.txt
COPY --from=img384 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img386
COPY --from=img385 data/Day5.data.txt data/Day5.data.txt
COPY --from=img385 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img387
COPY --from=img386 data/Day5.data.txt data/Day5.data.txt
COPY --from=img386 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img388
COPY --from=img387 data/Day5.data.txt data/Day5.data.txt
COPY --from=img387 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img389
COPY --from=img388 data/Day5.data.txt data/Day5.data.txt
COPY --from=img388 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img390
COPY --from=img389 data/Day5.data.txt data/Day5.data.txt
COPY --from=img389 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img391
COPY --from=img390 data/Day5.data.txt data/Day5.data.txt
COPY --from=img390 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img392
COPY --from=img391 data/Day5.data.txt data/Day5.data.txt
COPY --from=img391 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img393
COPY --from=img392 data/Day5.data.txt data/Day5.data.txt
COPY --from=img392 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img394
COPY --from=img393 data/Day5.data.txt data/Day5.data.txt
COPY --from=img393 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img395
COPY --from=img394 data/Day5.data.txt data/Day5.data.txt
COPY --from=img394 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img396
COPY --from=img395 data/Day5.data.txt data/Day5.data.txt
COPY --from=img395 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img397
COPY --from=img396 data/Day5.data.txt data/Day5.data.txt
COPY --from=img396 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img398
COPY --from=img397 data/Day5.data.txt data/Day5.data.txt
COPY --from=img397 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img399
COPY --from=img398 data/Day5.data.txt data/Day5.data.txt
COPY --from=img398 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img400
COPY --from=img399 data/Day5.data.txt data/Day5.data.txt
COPY --from=img399 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img401
COPY --from=img400 data/Day5.data.txt data/Day5.data.txt
COPY --from=img400 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img402
COPY --from=img401 data/Day5.data.txt data/Day5.data.txt
COPY --from=img401 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img403
COPY --from=img402 data/Day5.data.txt data/Day5.data.txt
COPY --from=img402 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img404
COPY --from=img403 data/Day5.data.txt data/Day5.data.txt
COPY --from=img403 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img405
COPY --from=img404 data/Day5.data.txt data/Day5.data.txt
COPY --from=img404 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img406
COPY --from=img405 data/Day5.data.txt data/Day5.data.txt
COPY --from=img405 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img407
COPY --from=img406 data/Day5.data.txt data/Day5.data.txt
COPY --from=img406 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img408
COPY --from=img407 data/Day5.data.txt data/Day5.data.txt
COPY --from=img407 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img409
COPY --from=img408 data/Day5.data.txt data/Day5.data.txt
COPY --from=img408 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img410
COPY --from=img409 data/Day5.data.txt data/Day5.data.txt
COPY --from=img409 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img411
COPY --from=img410 data/Day5.data.txt data/Day5.data.txt
COPY --from=img410 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img412
COPY --from=img411 data/Day5.data.txt data/Day5.data.txt
COPY --from=img411 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img413
COPY --from=img412 data/Day5.data.txt data/Day5.data.txt
COPY --from=img412 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img414
COPY --from=img413 data/Day5.data.txt data/Day5.data.txt
COPY --from=img413 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img415
COPY --from=img414 data/Day5.data.txt data/Day5.data.txt
COPY --from=img414 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img416
COPY --from=img415 data/Day5.data.txt data/Day5.data.txt
COPY --from=img415 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img417
COPY --from=img416 data/Day5.data.txt data/Day5.data.txt
COPY --from=img416 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img418
COPY --from=img417 data/Day5.data.txt data/Day5.data.txt
COPY --from=img417 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img419
COPY --from=img418 data/Day5.data.txt data/Day5.data.txt
COPY --from=img418 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img420
COPY --from=img419 data/Day5.data.txt data/Day5.data.txt
COPY --from=img419 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img421
COPY --from=img420 data/Day5.data.txt data/Day5.data.txt
COPY --from=img420 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img422
COPY --from=img421 data/Day5.data.txt data/Day5.data.txt
COPY --from=img421 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img423
COPY --from=img422 data/Day5.data.txt data/Day5.data.txt
COPY --from=img422 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img424
COPY --from=img423 data/Day5.data.txt data/Day5.data.txt
COPY --from=img423 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img425
COPY --from=img424 data/Day5.data.txt data/Day5.data.txt
COPY --from=img424 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img426
COPY --from=img425 data/Day5.data.txt data/Day5.data.txt
COPY --from=img425 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img427
COPY --from=img426 data/Day5.data.txt data/Day5.data.txt
COPY --from=img426 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img428
COPY --from=img427 data/Day5.data.txt data/Day5.data.txt
COPY --from=img427 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img429
COPY --from=img428 data/Day5.data.txt data/Day5.data.txt
COPY --from=img428 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img430
COPY --from=img429 data/Day5.data.txt data/Day5.data.txt
COPY --from=img429 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img431
COPY --from=img430 data/Day5.data.txt data/Day5.data.txt
COPY --from=img430 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img432
COPY --from=img431 data/Day5.data.txt data/Day5.data.txt
COPY --from=img431 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img433
COPY --from=img432 data/Day5.data.txt data/Day5.data.txt
COPY --from=img432 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img434
COPY --from=img433 data/Day5.data.txt data/Day5.data.txt
COPY --from=img433 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img435
COPY --from=img434 data/Day5.data.txt data/Day5.data.txt
COPY --from=img434 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img436
COPY --from=img435 data/Day5.data.txt data/Day5.data.txt
COPY --from=img435 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img437
COPY --from=img436 data/Day5.data.txt data/Day5.data.txt
COPY --from=img436 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img438
COPY --from=img437 data/Day5.data.txt data/Day5.data.txt
COPY --from=img437 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img439
COPY --from=img438 data/Day5.data.txt data/Day5.data.txt
COPY --from=img438 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img440
COPY --from=img439 data/Day5.data.txt data/Day5.data.txt
COPY --from=img439 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img441
COPY --from=img440 data/Day5.data.txt data/Day5.data.txt
COPY --from=img440 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img442
COPY --from=img441 data/Day5.data.txt data/Day5.data.txt
COPY --from=img441 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img443
COPY --from=img442 data/Day5.data.txt data/Day5.data.txt
COPY --from=img442 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img444
COPY --from=img443 data/Day5.data.txt data/Day5.data.txt
COPY --from=img443 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img445
COPY --from=img444 data/Day5.data.txt data/Day5.data.txt
COPY --from=img444 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img446
COPY --from=img445 data/Day5.data.txt data/Day5.data.txt
COPY --from=img445 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img447
COPY --from=img446 data/Day5.data.txt data/Day5.data.txt
COPY --from=img446 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img448
COPY --from=img447 data/Day5.data.txt data/Day5.data.txt
COPY --from=img447 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img449
COPY --from=img448 data/Day5.data.txt data/Day5.data.txt
COPY --from=img448 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img450
COPY --from=img449 data/Day5.data.txt data/Day5.data.txt
COPY --from=img449 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img451
COPY --from=img450 data/Day5.data.txt data/Day5.data.txt
COPY --from=img450 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img452
COPY --from=img451 data/Day5.data.txt data/Day5.data.txt
COPY --from=img451 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img453
COPY --from=img452 data/Day5.data.txt data/Day5.data.txt
COPY --from=img452 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img454
COPY --from=img453 data/Day5.data.txt data/Day5.data.txt
COPY --from=img453 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img455
COPY --from=img454 data/Day5.data.txt data/Day5.data.txt
COPY --from=img454 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img456
COPY --from=img455 data/Day5.data.txt data/Day5.data.txt
COPY --from=img455 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img457
COPY --from=img456 data/Day5.data.txt data/Day5.data.txt
COPY --from=img456 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img458
COPY --from=img457 data/Day5.data.txt data/Day5.data.txt
COPY --from=img457 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img459
COPY --from=img458 data/Day5.data.txt data/Day5.data.txt
COPY --from=img458 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img460
COPY --from=img459 data/Day5.data.txt data/Day5.data.txt
COPY --from=img459 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img461
COPY --from=img460 data/Day5.data.txt data/Day5.data.txt
COPY --from=img460 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img462
COPY --from=img461 data/Day5.data.txt data/Day5.data.txt
COPY --from=img461 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img463
COPY --from=img462 data/Day5.data.txt data/Day5.data.txt
COPY --from=img462 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img464
COPY --from=img463 data/Day5.data.txt data/Day5.data.txt
COPY --from=img463 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img465
COPY --from=img464 data/Day5.data.txt data/Day5.data.txt
COPY --from=img464 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img466
COPY --from=img465 data/Day5.data.txt data/Day5.data.txt
COPY --from=img465 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img467
COPY --from=img466 data/Day5.data.txt data/Day5.data.txt
COPY --from=img466 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img468
COPY --from=img467 data/Day5.data.txt data/Day5.data.txt
COPY --from=img467 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img469
COPY --from=img468 data/Day5.data.txt data/Day5.data.txt
COPY --from=img468 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img470
COPY --from=img469 data/Day5.data.txt data/Day5.data.txt
COPY --from=img469 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img471
COPY --from=img470 data/Day5.data.txt data/Day5.data.txt
COPY --from=img470 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img472
COPY --from=img471 data/Day5.data.txt data/Day5.data.txt
COPY --from=img471 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img473
COPY --from=img472 data/Day5.data.txt data/Day5.data.txt
COPY --from=img472 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img474
COPY --from=img473 data/Day5.data.txt data/Day5.data.txt
COPY --from=img473 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img475
COPY --from=img474 data/Day5.data.txt data/Day5.data.txt
COPY --from=img474 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img476
COPY --from=img475 data/Day5.data.txt data/Day5.data.txt
COPY --from=img475 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img477
COPY --from=img476 data/Day5.data.txt data/Day5.data.txt
COPY --from=img476 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img478
COPY --from=img477 data/Day5.data.txt data/Day5.data.txt
COPY --from=img477 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img479
COPY --from=img478 data/Day5.data.txt data/Day5.data.txt
COPY --from=img478 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img480
COPY --from=img479 data/Day5.data.txt data/Day5.data.txt
COPY --from=img479 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img481
COPY --from=img480 data/Day5.data.txt data/Day5.data.txt
COPY --from=img480 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img482
COPY --from=img481 data/Day5.data.txt data/Day5.data.txt
COPY --from=img481 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img483
COPY --from=img482 data/Day5.data.txt data/Day5.data.txt
COPY --from=img482 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img484
COPY --from=img483 data/Day5.data.txt data/Day5.data.txt
COPY --from=img483 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img485
COPY --from=img484 data/Day5.data.txt data/Day5.data.txt
COPY --from=img484 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img486
COPY --from=img485 data/Day5.data.txt data/Day5.data.txt
COPY --from=img485 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img487
COPY --from=img486 data/Day5.data.txt data/Day5.data.txt
COPY --from=img486 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img488
COPY --from=img487 data/Day5.data.txt data/Day5.data.txt
COPY --from=img487 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img489
COPY --from=img488 data/Day5.data.txt data/Day5.data.txt
COPY --from=img488 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img490
COPY --from=img489 data/Day5.data.txt data/Day5.data.txt
COPY --from=img489 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img491
COPY --from=img490 data/Day5.data.txt data/Day5.data.txt
COPY --from=img490 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img492
COPY --from=img491 data/Day5.data.txt data/Day5.data.txt
COPY --from=img491 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img493
COPY --from=img492 data/Day5.data.txt data/Day5.data.txt
COPY --from=img492 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img494
COPY --from=img493 data/Day5.data.txt data/Day5.data.txt
COPY --from=img493 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img495
COPY --from=img494 data/Day5.data.txt data/Day5.data.txt
COPY --from=img494 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img496
COPY --from=img495 data/Day5.data.txt data/Day5.data.txt
COPY --from=img495 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img497
COPY --from=img496 data/Day5.data.txt data/Day5.data.txt
COPY --from=img496 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img498
COPY --from=img497 data/Day5.data.txt data/Day5.data.txt
COPY --from=img497 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img499
COPY --from=img498 data/Day5.data.txt data/Day5.data.txt
COPY --from=img498 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img500
COPY --from=img499 data/Day5.data.txt data/Day5.data.txt
COPY --from=img499 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img501
COPY --from=img500 data/Day5.data.txt data/Day5.data.txt
COPY --from=img500 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img502
COPY --from=img501 data/Day5.data.txt data/Day5.data.txt
COPY --from=img501 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img503
COPY --from=img502 data/Day5.data.txt data/Day5.data.txt
COPY --from=img502 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img504
COPY --from=img503 data/Day5.data.txt data/Day5.data.txt
COPY --from=img503 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img505
COPY --from=img504 data/Day5.data.txt data/Day5.data.txt
COPY --from=img504 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx
FROM mcr.microsoft.com/dotnet/sdk:7.0.100 AS img506
COPY --from=img505 data/Day5.data.txt data/Day5.data.txt
COPY --from=img505 Day5.Script.fsx Day5.Script.fsx
RUN dotnet fsi Day5.Script.fsx